/**
 * @file    main.c
 * @brief   Application entry point – NUCLEO-F411RE TIM driver demo.
 *
 * ── What this does ───────────────────────────────────────────────────
 *
 *   1. PA5  (LD2)  – toggles every 500 ms (1 Hz blink) driven by a
 *                    TIM2-based blocking delay.
 *
 *   2. PA8  (PWM)  – 1 kHz, 50 % duty-cycle signal generated by
 *                    TIM1 CH1 in PWM Mode 1 running continuously while
 *                    the LED blinks.
 *
 * ── Clock assumptions ────────────────────────────────────────────────
 *
 *   HSI oscillator, 16 MHz (default after reset, no PLL).
 *   All AHB / APB prescalers = 1  →  all buses run at 16 MHz.
 *
 *   TIM2 (APB1): PSC=15, ARR=999  →  1 ms overflow  →  delay base
 *   TIM1 (APB2): PSC=15, ARR=999  →  1 kHz PWM period
 *
 * ── Verification ─────────────────────────────────────────────────────
 *
 *   LED blink : observe LD2 on the board; should toggle at ~500 ms.
 *   PWM       : connect oscilloscope to PA8 (CN10 pin 23 on NUCLEO-64);
 *               expected: 1 kHz square wave, 50 % duty cycle.
 */

#include "stm32f411xe.h"
#include "led.h"
#include "timer.h"
#include "pwm.h"

/* ====================================================================
 * Application Constants
 * ==================================================================== */

#define APP_BLINK_PERIOD_MS     (500U)   /**< LED toggle half-period [ms]  */
#define APP_PWM_FREQUENCY_HZ    (1000U)  /**< PWM carrier frequency  [Hz]  */
#define APP_PWM_DUTY_CYCLE_PCT  (50U)    /**< PWM duty cycle         [%]   */

/* ====================================================================
 * Entry Point
 * ==================================================================== */

int main(void)
{
    /* ── 1. Initialise on-board LED on PA5 ─────────────────────── */
    led_init();

    /* ── 2. Initialise TIM2 for 1 ms blocking delays ───────────── */
    timer_init();

    /* ── 3. Initialise TIM1 CH1 on PA8 for 1 kHz PWM ───────────── */
    pwm_init(APP_PWM_FREQUENCY_HZ);
    pwm_set_signal(APP_PWM_DUTY_CYCLE_PCT);
    pwm_start();                   /* Counter starts; signal appears on PA8 */

    /* ── 4. Super-loop: blink LED every 500 ms ──────────────────── */
    /*
     * PWM runs autonomously in hardware (TIM1 counter free-wheeling).
     * The CPU only services the LED blink; both tasks appear concurrent.
     */
    while (1)
    {
        led_toggle();
        timer_delay_ms(APP_BLINK_PERIOD_MS);
    }

    /* Unreachable – satisfies compiler return-type requirement */
    return 0;
}
